[2025-02-01 19:08:14,658: INFO: main: welcome]
[2025-02-01 21:40:10,679: ERROR: 2802484996: An error occurred: name 'read_yaml' is not defined]
[2025-02-01 21:40:35,429: ERROR: 2802484996: An error occurred: name 'read_yaml' is not defined]
[2025-02-01 21:40:37,258: ERROR: 2802484996: An error occurred: name 'read_yaml' is not defined]
[2025-02-04 10:59:26,084: ERROR: 2677232681: An error occurred: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x119382670> does not match annotation type <class 'pathlib.Path'>]
[2025-02-04 11:04:19,262: ERROR: 1939709391: An error occurred: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x119382670> does not match annotation type <class 'pathlib.Path'>]
[2025-02-04 11:16:07,230: ERROR: 1939709391: An error occurred: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x119382670> does not match annotation type <class 'pathlib.Path'>]
[2025-02-04 11:16:08,181: ERROR: 1939709391: An error occurred: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x119382670> does not match annotation type <class 'pathlib.Path'>]
[2025-02-04 11:16:19,660: ERROR: 1939709391: An error occurred: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x1052f3a60> does not match annotation type <class 'pathlib.Path'>]
[2025-02-04 11:16:48,471: ERROR: 929923544: An error occurred: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x1052f3a60> does not match annotation type <class 'pathlib.Path'>]
[2025-02-04 11:16:52,641: ERROR: 929923544: An error occurred: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x1052f3a60> does not match annotation type <class 'pathlib.Path'>]
[2025-02-04 11:16:54,074: ERROR: 929923544: An error occurred: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x1052f3a60> does not match annotation type <class 'pathlib.Path'>]
[2025-02-04 11:24:07,771: ERROR: 1112270519: An error occurred: [Errno 2] No such file or directory: 'path/to/config.yaml']
[2025-02-04 11:24:09,592: ERROR: 1112270519: An error occurred: [Errno 2] No such file or directory: 'path/to/config.yaml']
[2025-03-17 14:32:14,381: INFO: common: yaml file: src/DLPROJECT/configs/config.yaml loaded successfully]
[2025-03-17 14:32:14,384: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-17 14:32:14,385: INFO: common: created directory at: artifacts]
[2025-03-17 14:32:14,386: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-17 14:32:14,387: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-17 14:32:38,190: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-17 14:44:21,365: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-17 14:44:21,371: INFO: common: yaml file: src/DLPROJECT/configs/config.yaml loaded successfully]
[2025-03-17 14:44:21,372: INFO: common: yaml file: src/DLPROJECT/configs/params.yaml loaded successfully]
[2025-03-17 14:44:21,372: INFO: common: created directory at: artifacts]
[2025-03-17 14:44:21,372: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-17 14:44:21,372: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-17 14:44:44,764: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-17 14:44:45,015: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
